name: Gererating art
on:
  workflow_dispatch:
  schedule:
    - cron: '0 05 * * 1-5'
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: Wake up
        run: |
          curl --url 'https://www.riple.art/'
      - name: Wait for wake up
        run: sleep 2m
        shell: bash
      - name: Start art generation
        run: |
          curl --request POST \
          --url 'https://www.riple.art/api/protected/art/external/generate' \
          --header 'Authorization: Bearer ${{ secrets.API_SECRET_KEY }}'
      - name: Sleep
        run: sleep 2m
        shell: bash
      - name: Get generated art
        run: |
          curl --request POST \
          --url 'https://www.riple.art/api/protected/art/external/getGenerated' \
          --header 'Authorization: Bearer ${{ secrets.API_SECRET_KEY }}'
